services:

  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "${LOCALSTACK_HOST}:${LOCALSTACK_PORT1}:${LOCALSTACK_PORT1}"
      - "${LOCALSTACK_HOST}:${LOCALSTACK_PORT2}:${LOCALSTACK_PORT2}"
      
    environment:
      SERVICES: sqs,lambda,ses,iam,cloudwatch,logs
      LOCALSTACK_AUTH_TOKEN: ${LOCALSTACK_TOKEN}
      DEBUG: ${DEBUG:-0}
      LAMBDA_EXECUTOR: docker
      LAMBDA_DOCKER_NETWORK: minha-rede-local-docker 
    volumes:
      - "./localstack/volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - minha-rede-local-docker  
      
  # terraform:
  #   image: hashicorp/terraform:latest
  #   container_name: terraform
  #   working_dir: /infra
  #   entrypoint: ["/bin/sh", "-c"]
  #   command: "terraform init && terraform apply -auto-approve && tail -f /dev/null"
  #   environment:
  #     AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  #     AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  #     AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
  #     TF_VAR_localstack_endpoint: http://localstack:${LOCALSTACK_PORT1}
  #   volumes:
  #     - ./terraform:/infra
  #   networks:
  #     - minha-rede-local-docker
  #   depends_on:
  #     - localstack

  # terraform:
  #   image: hashicorp/terraform:latest
  #   container_name: terraform
  #   working_dir: /workspace
  #   environment:
  #     AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  #     AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  #     AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
  #     TF_VAR_localstack_endpoint: http://localstack:${LOCALSTACK_PORT1} # LocalStack endpoint
  #   volumes:
  #     - ./terraform:/workspace
  #   networks:
  #     - minha-rede-local-docker
  #   depends_on:
  #     - localstack
  #   entrypoint: ["terraform"]
  #   command: ["init"]
 
  mongodb:
    image: mongo:7
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - ${MONGO_HOST_HOST}:${MONGO_HOST_PORT}
    volumes:
      - mongodb-data:/data/db
    networks:
      - minha-rede-local-docker
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    ports:
      - ${MONGO_EXPRESS_HOST}:${MONGO_EXPRESS_PORT}
    networks:
      - minha-rede-local-docker

  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_HOST}:${REDIS_PORT}
    volumes:
      - redis-data:/data
    networks:
      - minha-rede-local-docker
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - ${REDISINSIGHT_HOST}:${REDISINSIGHT_PORT}
    volumes:
      - redisinsight-data:/data
    networks:
      - minha-rede-local-docker

  postgresdb:
    image: postgres:16
    container_name: postgres_db
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - minha-rede-local-docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: postgres_pgAdmin
    ports:
      - ${PGADMIN_PORT1}:${PGADMIN_PORT2}  
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - minha-rede-local-docker

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - ${RABBITMQ_AMQP_PORT}:${RABBITMQ_AMQP_PORT}
      - ${RABBITMQ_MANAGEMENT_UI_PORT}:${RABBITMQ_MANAGEMENT_UI_PORT}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - minha-rede-local-docker
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  users-api:
    image: projetofiap/users-api:4
    container_name: users-api
    volumes:
      - ./secrets/firebase-service-account.json:/app/firebase-service-account.json
    depends_on:
      localstack:
        condition: service_healthy
      postgresdb:
        condition: service_healthy
    environment:
      # Amazon SQS (LocalStack)
      SqsSettings__ServiceURL: ${SQS_SERVICE_URL}
      SqsSettings__EmailQueueURL: ${SQS_EMAIL_QUEUE_URL}
      SqsSettings__Region: ${SQS_REGION}
      SqsSettings__AccessKey: ${SQS_ACCESS_KEY}
      SqsSettings__SecretKey: ${SQS_SECRET_KEY}

      # Firebase
      Firebase__CredentialPath: ${FIREBASE_CREDENTIAL_PATH}
      Firebase__ApiKey: ${FIREBASE_APIKEY}

      # New Relic
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}
      NEW_RELIC_LOG: stdout
      NEW_RELIC_LOG_LEVEL: debug
      NEW_RELIC_APPLICATION_LOGGING_ENABLED: true
      NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED: true
      NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED: true

      # Db
      ConnectionStrings__DefaultConnection: Host=postgresdb;Port=${POSTGRES_CONTAINER_PORT};Database=${USERS_DB_NAME};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
    ports:
      - ${USERS_API_HOST_PORT}:${CONTAINER_PORT}
    networks:
      - minha-rede-local-docker

  payments-api:
    image: projetofiap/payments-api:fase3.v1
    container_name: payments-api
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgresdb:
        condition: service_healthy
    environment:
      # RabbitMQ
      RabbitmqSettings__Address: rabbitmq
      RabbitmqSettings__Port: ${RABBITMQ_AMQP_PORT}
      RabbitmqSettings__VirtualHost: /
      RabbitmqSettings__Username: ${RABBITMQ_DEFAULT_USER}
      RabbitmqSettings__Password: ${RABBITMQ_DEFAULT_PASS}

      # SQS
      SqsSettings__Region: ${SQS_REGION}
      SqsSettings__AccessKey: ${SQS_ACCESS_KEY}
      SqsSettings__SecretKey: ${SQS_SECRET_KEY}
      SqsSettings__ServiceURL: ${SQS_SERVICE_URL}
      SqsSettings__EmailQueueURL: ${SQS_EMAIL_QUEUE_URL}

      # Db
      ConnectionStrings__DefaultConnection: Host=postgresdb;Port=${POSTGRES_CONTAINER_PORT};Database=${PAYMENTS_DB_NAME};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};

      #Payment
      Payment__ApprovalRate: ${PAYMENT_APPROVAL_RATE}

      # New Relic
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}
      NEW_RELIC_LOG: stdout
      NEW_RELIC_LOG_LEVEL: debug
      NEW_RELIC_APPLICATION_LOGGING_ENABLED: true
      NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED: true
      NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED: true
    ports:
      - ${PAYMENTS_API_HOST_PORT}:${CONTAINER_PORT}
    networks:
      - minha-rede-local-docker

  catalog-api:
    image: projetofiap/catalog-api:fase3.v1
    container_name: catalog-api
    depends_on:
      postgresdb:
        condition: service_healthy
    environment:      
      # SQS
      SqsSettings__Region: ${SQS_REGION}
      SqsSettings__AccessKey: ${SQS_ACCESS_KEY}
      SqsSettings__SecretKey: ${SQS_SECRET_KEY}
      SqsSettings__ServiceURL: ${SQS_SERVICE_URL}
      SqsSettings__EmailQueueURL: ${SQS_EMAIL_QUEUE_URL}

      # Redis
      Redis__ConnectionString: redis:${REDIS_HOST},password=${REDIS_PASSWORD}

      # PostgreSQL
      ConnectionStrings__DefaultConnection: Host=postgresdb;Port=${POSTGRES_CONTAINER_PORT};Database=${CATALOG_DB_NAME};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};

      # MongoDB
      MongoDB__ConnectionString: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:${MONGO_HOST_HOST}/
      MongoDB__DatabaseName: ${CATALOG_DB_NAME}

      # New Relic
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}
      NEW_RELIC_LOG: stdout
      NEW_RELIC_LOG_LEVEL: debug
      NEW_RELIC_APPLICATION_LOGGING_ENABLED: true
      NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED: true
      NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED: true
    ports:
      - ${CATALOG_API_HOST_PORT}:${CONTAINER_PORT}
    networks:
      - minha-rede-local-docker

  

networks:
  minha-rede-local-docker:
    external: true
volumes:
  postgresql-data:
  postgresql-server-config:
  rabbitmq_data:
  mongodb-data:
  redis-data:
  redisinsight-data:

# commands
  # network-ls: docker network ls
  # network   : docker network create minha-rede-local-docker
  # build     : docker-compose -p fiap-challenge-fase-3 build
  # start     : docker-compose -p fiap-challenge-fase-3 up -d
  # recreate  : docker-compose -p fiap-challenge-fase-3 up -d --force-recreate