apiVersion: v1
kind: Service
metadata:
  name: mailhog
  labels:
    app: mailhog
  annotations:
    description: "Service para o MailHog, expondo a porta 1025 para envio de emails e a porta 8025 para acesso à interface web."
spec:
  type: NodePort
  selector:
    app: mailhog
  ports:
    - name: smtp
      protocol: TCP
      port: 1025 # A porta do service dentro do cluster Kubernetes.
      targetPort: 1025 # A porta do container, dentro do Pod, onde a aplicação está rodando.
      nodePort: 30025 # A porta exposta fora do cluster. Essa porta permite acessar a da máquina.
    - name: web
      protocol: TCP
      port: 8025
      targetPort: 8025
      nodePort: 30030      

# acessar localmente: http://localhost:30030/