apiVersion: apps/v1
kind: Deployment

metadata:
  name: mailhog
  annotations:
    description: "MailHog, um servidor de email de teste que captura emails enviados pela aplicação para visualização e depuração."

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mailhog

  template:
    metadata:
      labels:
        app: mailhog

    spec:
      containers:
      - name: mailhog
        image: mailhog/mailhog:latest

        ports:
          - containerPort: 1025
            name: smtp

          - containerPort: 8025
            name: web