apiVersion: v1
kind: Pod
metadata:
  name: mailhog
  labels:
    app: mailhog
  annotations:
    description: "Pod para o MailHog, um servidor de email de teste que captura emails enviados pela aplicação para visualização e depuração."
spec:
  containers:
    - name: mailhog
      image: mailhog/mailhog:latest
      ports:
        - containerPort: 1025
          name: smtp
        - containerPort: 8025
          name: web