apiVersion: v1
kind: Service
metadata:
  name: notification-api
  labels:
    app: notification-api
  annotations:
    description: "Service para a API de Notificações, expondo a porta 80 para acesso interno no cluster."
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  selector:
    app: notification-api

# acessar localmente: http://localhost:30080/scalar