apiVersion: v1
kind: Secret

metadata:
  name: localstack-secret
  labels:
    app: localstack
  annotations:
    description: "Secret com credenciais do LocalStack."

type: Opaque

stringData:
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"
  AWS_SESSION_TOKEN: ""
  LOCALSTACK_AUTH_TOKEN: "ls-gEkAdoFo-DofA-2701-ZEju-7020mujAa610"
