apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-config
  labels:
    app: shared
  annotations:
    description: "ConfigMap compartilhado para a API de Notificações, Usuário, Calatogo e Pagamento."
data:
  # rabbitmq
  RABBITMQ_ADDRESS: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_VIRTUAL_HOST: "/"