apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-config
  labels:
    app: shared
  annotations:
    description: "ConfigMap compartilhado para a API de Notificações, Usuário, Calatogo e Pagamento."
data:
  # rabbitmq
  RABBITMQ_ADDRESS: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_VIRTUAL_HOST: "/"
  # new relic
  NEW_RELIC_LOG: "stdout"
  NEW_RELIC_LOG_LEVEL: "debug"
  NEW_RELIC_APPLICATION_LOGGING_ENABLED: "true"
  NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED: "true"
  NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED: "true"