apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  containers:
    - name: rabbitmq
      image: rabbitmq:3-management
      env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: shared-secret
              key: RABBITMQ_USERNAME
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: shared-secret
              key: RABBITMQ_PASSWORD
      ports:
        - containerPort: 5672
        - containerPort: 15672