apiVersion: v1
kind: Secret
metadata:
  name: shared-secret
  labels:
    app: shared
  annotations:
    description: "Secret compartilhado para a API de Notificações, Usuário, Calatogo e Pagamento."
type: Opaque
stringData:
  # rabbitmq
  RABBITMQ_USERNAME: "admin"
  RABBITMQ_PASSWORD: "password"
  NEW_RELIC_LICENSE_KEY: "72e69c1c608f4ad9078c39b76d4ca3b1FFFFNRAL"
  NEW_RELIC_APP_NAME: "FiapCloudGames"
  POSTGRES_USER: "postgresAdmin"
  POSTGRES_PASSWORD: "postgresAdmin"
  PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  PGADMIN_DEFAULT_PASSWORD: "admin"