apiVersion: v1
kind: Pod
metadata:
  name: notification-api
  labels:
    app: notification-api
  annotations:
    description: "Pod para a API de Notificações, responsável por enviar emails e processar mensagens do RabbitMQ."
spec:
  containers: 
    - name: notification-api
      image: projetofiap/notification-api:5
      ports:
        - containerPort: 8080
      resources:
        requests: #minimum resources guaranteed to the container
          memory: "128Mi"
          cpu: "0.25"
        limits: #maximum resources that the container can use
          memory: "256Mi"
          cpu: "0.5"
      env:
        # RabbitMQ
        - name: RabbitmqSettings__Address
          valueFrom:
            configMapKeyRef:
              name: shared-config
              key: RABBITMQ_ADDRESS
        - name: RabbitmqSettings__Port
          valueFrom:
            configMapKeyRef:
              name: shared-config
              key: RABBITMQ_PORT
        - name: RabbitmqSettings__VirtualHost
          valueFrom:
            configMapKeyRef:
              name: shared-config
              key: RABBITMQ_VIRTUAL_HOST
        - name: RabbitmqSettings__Username
          valueFrom:
            secretKeyRef:
              name: shared-secret
              key: RABBITMQ_USERNAME
        - name: RabbitmqSettings__Password
          valueFrom:
            secretKeyRef:
              name: shared-secret
              key: RABBITMQ_PASSWORD

        # Email (MailHog)
        - name: EmailSettings__SmtpHost
          valueFrom:
            configMapKeyRef:
              name: notification-api-config
              key: MAILHOG_SMTP_HOST
        - name: EmailSettings__SmtpPort
          valueFrom:
            configMapKeyRef:
              name: notification-api-config
              key: MAILHOG_SMTP_PORT
        - name: EmailSettings__UseMailHog
          valueFrom:
            configMapKeyRef:
              name: notification-api-config
              key: MAILHOG_USEMAILHOG