apiVersion: v1
kind: Service

metadata:
  name: mongodb
  labels:
    app: mongodb
  
  annotations:
    description: "Service para o MongoDB, expondo a porta 27017 para comunicação com o banco de dados."

spec:
  type: ClusterIP

  selector:
    app: mongodb

  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      name: mongodb

  clusterIP: None
