apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-api-config
  labels:
    app: notification-api
  annotations:
    description: "ConfigMap para a API de Notificações, contendo configurações de ambiente para RabbitMQ e Email."
data:
  # Payment
  PAYMENT_APPROVAL_RATE: "0.9" # 90% de aprovação para simular falhas