apiVersion: v1
kind: Pod
metadata:
  name: postgresdb
  labels:
    app: postgresdb
  annotations:
    description: "Pod para o banco de dados PostgreSQL, utilizado pela API de Pagamentos para armazenar informações de transações e pagamentos."
spec:
  containers:
    - name: postgresdb
      image: postgres:latest
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_DB
          value: "payments-db"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: payments-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: payments-secret
              key: POSTGRES_PASSWORD
      resources:
        requests: #minimum resources guaranteed to the container
          memory: "256Mi"
          cpu: "0.25"
        limits: #maximum resources that the container can use
          memory: "512Mi"
          cpu: "0.5"