apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-payments
  labels:
    app: postgresdb-payments
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Ajuste conforme necessário