apiVersion: v1
kind: Secret
metadata:
  name: payments-secret
  labels:
    app: payments
  annotations:
    description: "Secret para a API de Pagamentos."
type: Opaque
stringData:
  # Db
  DB_USER_CONNECTION_STRING: "Host=postgresdb-payments;Port=5432;Database=payments-db;Username=postgresAdmin;Password=postgresAdmin;"