apiVersion: apps/v1
kind: Deployment

metadata:
  name: catalog-deployment

  labels:
    app: catalog-api

  annotations:
    description: "Deployment para a API de Catálogo, garantindo alta disponibilidade e escalabilidade para o serviço de gerenciamento de produtos."

spec:
  replicas: 1

  selector:
    matchLabels:
      app: catalog-api

  template:
    metadata:
      labels:
        app: catalog-api

    spec:
      containers:
        - name: catalog
          image: projetofiap/catalog-api:latest
          
          ports:
            - containerPort: 8080
          
          resources:
            requests: #minimum resources guaranteed to the container
              memory: "128Mi"
              cpu: "250m"
            limits: #maximum resources that the container can use
              memory: "256Mi"
              cpu: "500m"
          
          env:
            # RabbitMQ
            - name: RabbitmqSettings__Address
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: RABBITMQ_ADDRESS
            
            - name: RabbitmqSettings__Port
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: RABBITMQ_PORT
            
            - name: RabbitmqSettings__VirtualHost
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: RABBITMQ_VIRTUAL_HOST
            
            - name: RabbitmqSettings__Username
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: RABBITMQ_USERNAME
            
            - name: RabbitmqSettings__Password
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: RABBITMQ_PASSWORD
            
            # Db
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: catalog-secret
                  key: DB_USER_CONNECTION_STRING

            # New Relic
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: NEW_RELIC_LICENSE_KEY
            - name: NEW_RELIC_APP_NAME
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: NEW_RELIC_APP_NAME 
            - name: NEW_RELIC_LOG
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: NEW_RELIC_LOG
            - name: NEW_RELIC_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: NEW_RELIC_LOG_LEVEL
            - name: NEW_RELIC_APPLICATION_LOGGING_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: NEW_RELIC_APPLICATION_LOGGING_ENABLED
            - name: NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED
            - name: NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED