apiVersion: v1
kind: Secret

metadata:
  name: catalog-secret

  labels:
    app: catalog

  annotations:
    description: "Secret para a API de Catálogo."

type: Opaque
stringData:
  # Db
  DB_USER_CONNECTION_STRING: "Host=postgresdb-catalog;Port=5432;Database=catalog-db;Username=postgresAdmin;Password=postgresAdmin;"