apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-configmap
  labels:
    app: notification-api
  annotations:
    description: "ConfigMap para a API de Notificações, contendo configurações de ambiente para RabbitMQ e Email."
data:
  # Email (MailHog)
  MAILHOG_SMTP_HOST: "mailhog"
  MAILHOG_SMTP_PORT: "1025"
  MAILHOG_USEMAILHOG: "true"