apiVersion: v1
kind: Secret
metadata:
  name: users-secret
  labels:
    app: users
  annotations:
    description: "Secret para a API de Usuários."
type: Opaque
stringData:
  # Db
  DB_USER_CONNECTION_STRING: "Host=postgresdb;Port=5432;Database=user-db;Username=postgresAdmin;Password=postgresAdmin;"
  
  # FireBase
  FIREBASE_CREDENTIAL_PATH: "firebase-service-account.json"
  FIREBASE_API_KEY: "AIzaSyCP88H3UcP8q3sl4Yh9Kf6IEePA_5KwTEs"