apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - deployment.yaml
  - service.yaml
  # Descomente a linha abaixo somente se quiser expor a UI via NLB interno
  - service-lb-ui.yaml
