apiVersion: v1
kind: Pod
metadata:
  name: postgresdb-catalog
  labels:
    app: postgresdb-catalog
  annotations:
    description: "Pod para o banco de dados PostgreSQL, utilizado pela API de Catálogo para armazenar informações de catálogo."
spec:
  containers:
    - name: postgresdb-catalog
      image: postgres:16
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_DB
          value: "catalog-db"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: shared-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: shared-secret
              key: POSTGRES_PASSWORD
      resources:
        requests: #minimum resources guaranteed to the container
          memory: "256Mi"
          cpu: "0.25"
        limits: #maximum resources that the container can use
          memory: "512Mi"
          cpu: "0.5"
      volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumes:
  - name: postgres-storage
    persistentVolumeClaim:
      claimName: postgres-pvc-catalog